version: '3.5'

services:
  api-01: &api
    build:
      context: ./RinhaBackend.Api
      dockerfile: ../Dockerfile
    container_name: api-01
    environment:
      - HTTP_PORTS=5000
    ports:
      - 5001:5000
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '90MB'

  api-02:
    # Copy from 'api-01'.
    <<: *api
    container_name: api-02
    ports:
      - 5002:5000

  nginx:
    image: nginx:1.24
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-01
      - api-02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '70MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
